# Generated by Django 4.2.3 on 2023-10-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiologistDoctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingstemplate',
            name='doctor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
