# Generated by Django 4.2.3 on 2023-08-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyRecord',
            fields=[
                ('record_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('modality', models.CharField(max_length=50, null=True)),
                ('request_time', models.DateTimeField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
        ),
    ]
