# Generated by Django 4.2.3 on 2023-08-25 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0005_alter_radiologyrecord_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Record',
            fields=[
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medicalTech.radiologyrecord')),
                ('image', models.BinaryField()),
                ('prediction', models.CharField(max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='radiologyrecord',
            name='notes',
        ),
    ]
