# Generated by Django 4.2.3 on 2023-08-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0006_image_record_remove_radiologyrecord_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_record',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
