# Generated by Django 4.2.3 on 2023-08-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0007_alter_image_record_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_record',
            name='image',
            field=models.BinaryField(),
        ),
    ]
