# Generated by Django 4.2.3 on 2023-08-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0008_alter_image_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_record',
            name='image_filename',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
