# Generated by Django 4.2.3 on 2023-09-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0010_alter_image_record_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyrecord',
            name='nationality',
            field=models.CharField(default='Singaporean', max_length=255),
            preserve_default=False,
        ),
    ]
