# Generated by Django 4.2.3 on 2023-09-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0011_radiologyrecord_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyrecord',
            name='area',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiologyrecord',
            name='gender',
            field=models.CharField(default='None', max_length=10),
            preserve_default=False,
        ),
    ]
