# Generated by Django 4.2.3 on 2023-09-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0012_radiologyrecord_area_radiologyrecord_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyrecord',
            name='modality',
            field=models.CharField(default='CXR', max_length=50),
        ),
    ]
