# Generated by Django 4.2.3 on 2023-09-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0013_alter_radiologyrecord_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('In Progress', 'In Progress'), ('completed', 'Completed'), ('EMERGENCY', 'EMERGENCY')], default='pending', max_length=20),
        ),
    ]
