# Generated by Django 4.2.3 on 2023-10-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0015_alter_image_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_record',
            name='examination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image_record',
            name='findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='image_record',
            name='impressions',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image_record',
            name='indications',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
