# Generated by Django 4.2.3 on 2023-10-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0016_image_record_examination_image_record_findings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyrecord',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Queueing', 'Queueing'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('EMERGENCY', 'EMERGENCY')], default='Registered', max_length=20),
        ),
    ]
