# Generated by Django 4.2.3 on 2023-10-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0017_alter_radiologyrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyrecord',
            name='observation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='radiologyrecord',
            name='senderDoctor',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
