# Generated by Django 4.2.3 on 2023-10-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0018_radiologyrecord_observation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiologyrecord',
            old_name='observation',
            new_name='indications',
        ),
        migrations.RemoveField(
            model_name='image_record',
            name='indications',
        ),
    ]
