# Generated by Django 4.2.3 on 2023-10-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0019_rename_observation_radiologyrecord_indications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_record',
            name='upload_date',
            field=models.DateTimeField(null=True),
        ),
    ]
