# Generated by Django 4.2.3 on 2023-10-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0021_image_record_medtech'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_record',
            name='radiologyDoctor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
