# Generated by Django 4.2.3 on 2023-11-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0022_image_record_radiologydoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_record',
            name='findings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
