# Generated by Django 4.2.3 on 2023-11-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0022_image_record_radiologydoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_record',
            name='deletation_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='radiologyrecord',
            name='update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
