# Generated by Django 4.2.3 on 2023-11-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0023_alter_image_record_findings'),
        ('medicalTech', '0023_image_record_deletation_time_and_more'),
    ]

    operations = [
    ]
