# Generated by Django 4.2.3 on 2023-11-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0026_image_record_deletation_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiologyrecord',
            old_name='upload_time',
            new_name='update_time',
        ),
    ]
