# Generated by Django 4.2.3 on 2023-11-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTech', '0027_rename_upload_time_radiologyrecord_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_record',
            old_name='deletation_time',
            new_name='deletion_time',
        ),
    ]
