# Generated by Django 4.2.3 on 2023-08-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='account_id',
            new_name='account',
        ),
    ]
