# Generated by Django 4.2.3 on 2023-08-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0011_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('systemAdmin', 'System Admin'), ('medicalTech', 'Medical Technician'), ('healtcareAdmin', 'Healtcare Admin'), ('radiologoistDoctor', 'Radiologist Doctor')], default='systemAdmin', max_length=50),
        ),
    ]
