# Generated by Django 4.2.3 on 2023-08-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0014_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('systemAdmin', 'System Admin'), ('medicalTech', 'Medical Technician'), ('healthcareAdmin', 'Healthcare Admin'), ('radiologyDoctor', 'Radiology Doctor')], default='systemAdmin', max_length=50),
        ),
    ]
