# Generated by Django 4.2.3 on 2023-08-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0015_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
